### ISSUE TITLE
Tag a release

### ISSUE THREAD

**Issue by laszlof** [alexander-schranz/iso-3166-2#2]
Can you tag a release on this including https://github.com/alexander-schranz/iso-3166-2/pull/1 ?

That way we can install without having to pull the master branch via composer. 

Thanks!

**Comment by alexander-schranz** [comment]
@laszlof released under: [1.0.1](https://github.com/alexander-schranz/iso-3166-2/releases) 

EDIT: also added to packagist: https://packagist.org/packages/l91/iso-3166-2

**Comment by laszlof** [comment]
Thanks!
