### ISSUE TITLE
deprecated

### ISSUE THREAD

**Issue by pfpro** [alexander-schranz/iso-3166-2#4]
Hey there,

PHP8.2
SYMFONY 6.2.7
WSL2/UBUNTU

i like your package, but retrieve a deprecated log entry while calling getSubdivisions() - without the locale parameter:
"Deprecated: strtolower(): Passing null to parameter #1 ($string) of type string is deprecated"

Could you maybe modify your getSubdivisions method to avoid the message in the logs?

public static function getSubdivisions($countryCode, $locale = null)
{
    return self::loadSubdivisionFile(
        strtolower($countryCode), 
        strtolower($locale)
    );
}

Best regards

**Comment by alexander-schranz** [comment]
Hello @pfpro 👋 ,

I'm fine to review a pull request if somebody want to submit one.
